### ISSUE TITLE
DigitalOcean provider

### ISSUE THREAD

**Issue by SvenDowideit** [libdns/libdns#10]
I've just made a simple one, using https://github.com/digitalocean/godo as I want it to migrate a zone from DO to gandi

its at https://github.com/onaci/digitalocean

**Comment by mholt** [comment]
Awesome! Just one note, add a godoc for the fields on the struct: https://github.com/onaci/digitalocean/blob/d0735c2503f081b26a95370dbcf669f1ffe8109e/provider.go#L13

Otherwise, LGTM. Is it alright if I make a repo for it in the `libdns` org and then you can move it there? It's important to the project that they're all in one place -- you'll of course be made an admin of the repo.

If you have a few extra minutes, consider a Caddy module as well! https://caddy.community/t/writing-new-dns-provider-modules-for-caddy/7786 -- if you're busy though, I can probably make about 5 minutes to do it. If you want to do it though, let me know and I'll make a repo for that as well.

**Comment by SvenDowideit** [comment]
yup, I'm happy to take care of pushing the code to libdnd/digitalocean, and writing a dns provider module for caddy too - if i run out of tuits, we can talk :)

**Comment by mholt** [comment]
Cool, I made the repos and sent you invites!

**Comment by SvenDowideit** [comment]
and of course I've just been hit with other things, so hopefully i'll get to it before monday :)

**Comment by mholt** [comment]
No rush! Good luck.
