### ISSUE TITLE
DNSPOD Provider

### ISSUE THREAD

**Issue by lscgzwd** [libdns/libdns#11]
My repo: https://github.com/lscgzwd/libdns-dnspod

I want to push at libdns/dnspod.

I have tested the code.

**Comment by mholt** [comment]
Awesome! At a quick glance, looks good, checks all the important boxes. Fill out a simple README when you have the chance.

Would you be willing to make an equivalent caddy-dns package so that it can be used in Caddy? Not required, but very useful and pretty easy to do: https://caddy.community/t/writing-new-dns-provider-modules-for-caddy/7786

**Comment by lscgzwd** [comment]
> Awesome! At a quick glance, looks good, checks all the important boxes. Fill out a simple README when you have the chance.
> 
> Would you be willing to make an equivalent caddy-dns package so that it can be used in Caddy? Not required, but very useful and pretty easy to do: https://caddy.community/t/writing-new-dns-provider-modules-for-caddy/7786

I have finish the README, and already make the caddy-dns package: https://github.com/lscgzwd/caddy-dnspod

**Comment by lscgzwd** [comment]
Pushed to libdns/dnspod ,  Can I push caddy-dns/dnspod ?

**Comment by mholt** [comment]
Yep! Repo made, and sent you the invite. Thanks again! When you're done pushing it (make sure the Go module path is updated in go.mod) you can register it on the Caddy website so people can easily use it.

**Comment by lscgzwd** [comment]
Thanks!
I have pushed to caddy-dns/dnspod and registered it on the Caddy website.

**Comment by mholt** [comment]
Excellent, thank you!! That's awesome.
