### ISSUE TITLE
New Provider: regfish

### ISSUE THREAD

**Issue by amallek** [libdns/libdns#138]
Hi everyone! We've created a libdns provider for Regfish DNS ([Regfish API docs](https://regfish.readme.io/), based on [regfish-dnsapi-go](https://github.com/regfish/regfish-dnsapi-go))

We're looking forward to integrating with Caddy in the future.

Thanks!
Andy

**Comment by mholt** [comment]
Excellent!

In order to be published (with libdns), we'll need to move it into the `libdns/regfish` repo, which I'll create shortly. Make sure to update your package path at go.mod to be correct.

I'll also create a caddy-dns repo for you to push a Caddy module to. (you can find the template in the caddy-dns org)

I might recommend separating the regfish API client from the type that implements the libdns interfaces so that you can maintain both independently.

**Comment by amallek** [comment]
Updated the `libdns/regfish` repo with its initial commit.

**Comment by amallek** [comment]
@mholt I updated the `caddy-dns/regfish` repo as well.

**Comment by mholt** [comment]
Awesome, thanks for contributing!
