### ISSUE TITLE
How about adding priority to the Record struct?

### ISSUE THREAD

**Issue by kmpm** [libdns/libdns#38]
If you would like to use libdns for something like MX records it would be really nice to have some kind of way to manage priority.

**Comment by mholt** [comment]
True, we could add an optional Priority field to the Record struct. Do you have an actual need for this?

**Comment by kmpm** [comment]
No current need. 
But if it's gonna be one lib to rule them all then it will be necessary.

**Comment by mholt** [comment]
I've added a Priority field. If that looks good, I can tag v0.2.1 I guess.

**Comment by kmpm** [comment]
Good enough for me.

**Comment by nathanejohnson** [comment]
I know this is closed, but having just created a provider for powerdns does this mean I (as well as all other providers) need to parse out the priority in the responses back from upstream and convert it to the new format?  Should it support both formats on the way in?  Also, since 0 is a valid priority for an MX record, knowing which format the user is giving us gets slightly tricky.  Some guidance / documentation on what providers should do in the following scenarios would be helpful:

using the MX example,

What if the caller passes in a []records slice with

0 mx.example.com

and priority of 0

what if they pass priority of 0, mx of 

10 mx.eample.com


And should all response list types have the priority parsed out and no more concatenation?  What about SOA records or the like?

Sorry if this isn't the proper forum for discussion

**Comment by mholt** [comment]
@nathanejohnson 

> I know this is closed, but having just created a provider for powerdns does this mean I (as well as all other providers) need to parse out the priority in the responses back from upstream and convert it to the new format? Should it support both formats on the way in?

What "format"? Can you be more specific?

> what if they pass priority of 0, mx of `10 mx.eample.com`

That doesn't make any sense, what do you mean "MX of"?
