### ISSUE TITLE
google domains

### ISSUE THREAD

**Issue by gedw99** [libdns/libdns#40]
wondering if a plugin for google domains and its DNS is needed ?

**Comment by francislavoie** [comment]
I would recommend using DNS challenge delegation for Google domains, since they don't have a sensible API. The `duckdns` plugins explicitly supports this:

https://github.com/caddy-dns/duckdns#challenge-delegation

**Comment by mholt** [comment]
Will be working on this shortly.

**Comment by mholt** [comment]
(... still waiting, I was reached out to by the Google Domains team about a possible API, but haven't heard back)

**Comment by mholt** [comment]
Google has [finally announced]() their implementation of a (basic) API to manipulate DNS records, but only for the purposes of ACME challenges.

This has been implemented in [caddy-dns/google-domains](https://github.com/caddy-dns/google-domains). We were fortunate enough to be able to test this integration before the launch.

I'm going to close this issue, since I think it was originally opened for the purpose of solving ACME challenges and getting certificates, which is now functional. And since they don't have a general DNS record manipulation API, we can't implement that anyway.

**Comment by mholt** [comment]
Sigh. Unsurprisingly, Google Domains is shutting down in a few months: https://newsroom.squarespace.com/blog/googledomains

What a trashfire of a product.
